### ISSUE TITLE
笔记设置功能待完善

### ISSUE THREAD

**Issue by honkaoi** [weshareProject/weshareEdgePlugin#2]
笔记设置功能
自定义合拢展开(小钉子状态)
进一步块优化
性能优化

**Comment by Cnotta** [comment]
目前已将存储功能转移至 background

**Comment by Cnotta** [comment]
笔记设置功能基本完善
目前有字体设置、颜色设置、预览
并且可以查看记录笔记的网站并进行跳转
优化了部分background的响应（增加了唤醒代码）
但不能确保background传输数据及时，不过依然可以使用刷新页面解决传输问题
